config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  devise_for :users
  get "home/about" => "homes#about"

  root to: 'homes#top'
   resources :books, only: [:new, :create, :index, :show, :edit, :destroy] do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
   resource :relationships, only: [:create, :destroy]
  get "followings" => "relationships#followings", as: "followings"
  get "followers" => "relationships#followers", as: "followers"
end

  get '/search' => 'search#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user
attachment :image
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

validates :title, presence: true
validates :body, presence: true, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :follower, class_name: "User"
belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

attachment :profile_image

validates :name, uniqueness: true, length: { in: 2..20 }  
validates :introduction, length: { maximum: 50 }

has_many :books, dependent: :destroy
has_many :book_comments, dependent: :destroy
has_many :favorites, dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
has_many :followers, through: :reverse_of_relationships, source: :follower
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :followings, through: :relationships, source: :followed


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
  if  comment.save
    redirect_back(fallback_location: root_path)
  else
    redirect_back(fallback_location: root_path)
  end
  end

  def destroy
  BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to books_path

  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user =current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash.now[:danger] = "error"
      render :index
    end
  end

  def index
   @book=Book.new
   @books=Book.all
   @user =current_user
  end

  def show
  @new_book = Book.new
  @book = Book.find(params[:id])
  @user =current_user
  @book_comment = BookComment.new
  end

  def edit
  @book = Book.find(params[:id])
  @user =current_user
  if @book.user != current_user
   redirect_to books_path
  end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      flash.now[:danger] = "error"
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)

  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
def top
end

def about
end


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end

private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'User'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
  @users =User.all
  @book = Book.new
  @user = current_user
  end

  def show
    @new_book = Book.new
    @user =User.find(params[:id])
    @books =@user.books
    @book =Book.new

  end

  def edit
   @user = User.find(params[:id])
   if @user != current_user
   redirect_to user_path(current_user)
   end
  end

  def update
   @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
      <%= form_with model:@book, local: true do |f| %>
         <label for="book_title">Title</label>
    	   <div class="form-group">
         <%= f.text_field :title %>
         </div>

         <label for="book_opinion">Opinion</label>
         <div class="form-group">
         <%= f.text_area :body %>
         </div>

        <div class="form-group">
        <%= f.submit 'Update Book' %>
        </div>
      <%end%>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>

      </div>
    </div>
  </div>
  </main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
   <div class="row">
    <div class="col-md-3">
    <%= render 'users/list', book: @book, user: @user %>
  </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
      <thead>
          <tr>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
          </tr>
      </thead>
      <tbody>
          <% @books.each do |book| %>
            <tr>
                <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
                <% end %>
                  </td>
                <td>
                  <%= link_to book_path(book.id) do%>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
                <td><%= book.book_comments.count %>コメント</td>
 <% if book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(book), method: :delete do %>
        ♥<%= book.favorites.count %> いいね
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(book), method: :post do %>
        ♡<%= book.favorites.count %> いいね
      <% end %>
    </td>
  <% end %>

            </tr>
          <%end%>
      </tbody>


      </table>
   </div>
  </div>
</main>

app/views/books/show.html.erb
<%= flash[:notice] %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
    <%= render 'users/list', book: @new_book,user: @book.user %>
  </div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
      <thead>
          <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
          </tr>
      </thead>

 <tbody>
    <tr>
      <td>
      <%= link_to user_path(@book.user_id) do %>
      <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <div><%= @book.user.name %></div>
      <% end %>
      </td>
      <td>
        <%= link_to  book_path(@book.id)  do%>
        <%= @book.title %>
        <%end%>
      </td>
      <td><%= @book.body %></td>
      <td>コメント件数：<%= @book.book_comments.count %></td>
      <% if @book.favorited_by?(current_user) %>
    <td>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        ♥<%= @book.favorites.count %> いいね
      <% end %>
    </td>
    <% else %>
    <td>
      <%= link_to book_favorites_path(@book), method: :post do %>
        ♡<%= @book.favorites.count %> いいね
      <% end %>
    </td>
  <% end %>
      <% if @book.user.id == current_user.id %>
      <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
      <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか?" %></td>
      <% end %>
    </tr>
  </tbody>
  </table>
<div class="comments">

<% @book.book_comments.each do |book_comment| %>
  <td><%= image_tag('no_image.jpg') %></td>
  <%= book_comment.user.name %>
  <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
  <% if book_comment.user == current_user %>
  <div class="comment-delete">
    <td><%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %></td>
  </div>
  <% end %>

<% end %>
</div>
<div class="new-comment">
<div class = "form-group">
<%= form_with(model:[@book, @book_comment], local: true) do |f| %>
  <td><%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class:"form-control" %></td>
  <td><%= f.submit "送信する" %></td>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/homes/about.html.erb
<main>
<p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container"> 
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !!
          </h1>
          <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          ,
          </p>
          <p>you can share and exchange your opinions , inpressions , and
          emotions</p>
          <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
            </div>
        </div>
    </div>
  </div>  
</div>
</main>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= book.title %>
                </th>
                <th>
                    <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_list.html.erb
      <h2>User info</h2>

       <table class="table">
      <tbody>
       <tr>
       <th><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></th>
        </tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %><th>
        </tr>
        <tr>
          <th>フォロー数: <%= link_to user.followings.count,  user_followings_path(user.id) %></th>
        </tr>
        <tr>
          <th>フォロワー数: <%= link_to user.followers.count,  user_followers_path(user.id) %></th>
        </tr>
        <tr>
          <% if current_user != user %>
          <% if current_user.following?(user) %>
           <th><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></th>
           <% else %>
           <th><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></th>
           <% end %>
           <% end %>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to '', edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    </div>


   <%= form_with model:book, url:'/books', local:true do |f| %>

    <h2 class="mt-3">New book<h2>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
      </div>
      <div class="form-group">
        <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
      </div>


    <% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>User info</h2>

         <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
        <%end%>

    </div>
  </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
    <%= render 'users/list', user: current_user, book: @book %>
  </div>
<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
     <tr>
     <td><%= attachment_image_tag user, :profile_image, :size => "50x50" , fallback: "no_image.jpg" %></td>
     <td><%= user.name %></td>
     <% if current_user.following?(user) %>
     <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
     <% else %>
     <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
     <% end %>
     <td><%= link_to "Show", user_path(user.id) %></td>
     </tr>
    <%end%>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<p id="notice"></p>
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
    <%= render 'users/list', book: @new_book,user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3">
      </th>
    </thead>
    <tbody>
     <% @books.each do |book| %>
      <tr>
        <td>
        <%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
        <% end %>
        </td>

        <td>
        <%= link_to book_path(book.id)  do%>
           <%= book.title %>
        <% end %>
        </td>
         <td><%= book.body %></td>
      </tr>
     <% end %>
    </tbody>
  </table>
</div>
</div>
</div>